import { Job, JobPlace, Tech } from './app.models';

export const jobList: Job[] = [
  {
    place: JobPlace.Chessit,
    from: new Date('2025-03-01'),
    to: null,
    location: 'Danderyd',
    role: 'Front end-utvecklare',
    techniques: [
      Tech.Angular,
      Tech.TypeScript,
      Tech.SASS,
      Tech['.NET'],
      Tech.Scrum,
    ],
  },
  {
    place: JobPlace.SEB,
    from: new Date('2023-04-04'),
    to: new Date('2024-12-31'),
    location: 'Solna',
    role: 'Front end-utvecklare',
    techniques: [
      Tech.Angular,
      Tech.TypeScript,
      Tech.SQL,
      Tech.SASS,
      Tech['.NET'],
      Tech.Scrum,
      Tech.Blazor,
    ],
  },
  {
    place: JobPlace.SvenskaGolf,
    from: new Date('2022-01-01'),
    to: new Date('2022-04-01'),
    location: 'Stockholm',
    role: 'Front end-utvecklare',
    techniques: [Tech.Vue, Tech.Vuex, Tech.SASS, Tech.JSON],
  },
  {
    place: JobPlace.Arbetsformedlingen,
    from: new Date('2019-12-01'),
    to: new Date('2021-08-01'),
    location: 'Stockholm',
    role: 'Frontendutvecklare',
    techniques: [
      Tech.Angular,
      Tech.TypeScript,
      Tech['.NET'],
      Tech.Java,
      Tech.CSS,
      Tech.Jenkins,
      Tech.Git,
      Tech.JSON,
      Tech.REST,
      Tech.TypeScript,
      Tech.WCAG,
    ],
  },
  {
    place: JobPlace.BrandFactory,
    from: new Date('2019-04-01'),
    to: new Date('2019-11-01'),
    location: 'Stockholm',
    role: 'Front end-utvecklare',
    techniques: [
      Tech.JavaScript,
      Tech.JSON,
      Tech.SASS,
      Tech.Bootstrap,
      Tech.EpiserverCMS,
      Tech.Vue,
    ],
  },
  {
    place: JobPlace.Riksarkivet,
    from: new Date('2018-10-01'),
    to: new Date('2019-03-01'),
    location: 'Stockholm',
    role: 'Angular-utvecklare',
    techniques: [
      Tech.Angular,
      Tech.TypeScript,
      Tech.ASPNETMVC,
      Tech.SQL,
      Tech.RxJs,
      Tech.TypeScript,
      Tech.SASS,
    ],
  },
  {
    place: JobPlace.Aspia,
    from: new Date('2018-04-01'),
    to: new Date('2018-10-01'),
    location: 'Stockholm',
    role: 'Front end-utvecklare',
    techniques: [
      Tech.JavaScript,
      Tech.CSS,
      Tech.SASS,
      Tech.Vue,
      Tech.Webpack,
      Tech.Bootstrap,
    ],
  },
  {
    place: JobPlace.Interflora,
    from: new Date('2017-04-01'),
    to: new Date('2018-04-01'),
    location: 'Stockholm',
    role: 'Front end-utvecklare',
    techniques: [
      Tech.AngularJS,
      Tech.Bootstrap,
      Tech.SASS,
      Tech.Gulp,
      Tech.EpiserverCMS,
    ],
  },
  {
    place: JobPlace.SoderbergPartners,
    from: new Date('2017-01-01'),
    to: new Date('2017-04-01'),
    location: 'Stockholm',
    role: 'Front end-utvecklare',
    techniques: [
      Tech.ASPNETMVC,
      Tech.jQuery,
      Tech.SASS,
      Tech.Bootstrap,
      Tech.Highcharts,
      Tech.JavaScript,
    ],
  },
  {
    place: JobPlace.ICA,
    from: new Date('2016-09-01'),
    to: new Date('2016-12-01'),
    location: 'Sundbyberg',
    role: 'Front end-utvecklare',
    techniques: [
      Tech.HTML,
      Tech.CSS,
      Tech.JavaScript,
      Tech.jQuery,
      Tech.ASPNETCore,
      Tech.Grunt,
      Tech.SASS,
    ],
  },
  {
    place: JobPlace.Sats,
    from: new Date('2015-06-01'),
    to: new Date('2016-02-01'),
    location: 'Stockholm',
    role: 'Webbutvecklare',
    techniques: [
      Tech.AngularJS,
      Tech.ASPNETMVC,
      Tech.HTML,
      Tech.CSS,
      Tech.JavaScript,
      Tech.Photoshop,
    ],
  },
  {
    place: JobPlace.Printpool,
    from: new Date('2015-02-01'),
    to: new Date('2015-06-01'),
    location: 'Stockholm',
    role: 'Webbutvecklare',
    techniques: [
      Tech.AngularJS,
      Tech.ASPNETMVC,
      Tech.HTML,
      Tech.CSS,
      Tech.JavaScript,
      Tech.Photoshop,
    ],
  },
  {
    place: JobPlace.SverigesKommunikatorer,
    from: new Date('2014-10-01'),
    to: new Date('2015-01-01'),
    location: 'Stockholm',
    role: 'Webbutvecklare',
    techniques: [
      Tech.ASPNETMVC,
      Tech.EpiserverCMS,
      Tech.AngularJS,
      Tech.HTML,
      Tech.CSS,
      Tech.JavaScript,
      Tech.Photoshop,
      Tech.JavaScript,
    ],
  },
  {
    place: JobPlace.Sats,
    from: new Date('2014-05-01'),
    to: new Date('2014-08-01'),
    location: 'Stockholm',
    role: 'Webbutvecklare',
    techniques: [
      Tech.ASPNETMVC,
      Tech.EpiserverCMS,
      Tech.AngularJS,
      Tech.HTML,
      Tech.CSS,
      Tech.JavaScript,
      Tech.Photoshop,
    ],
  },
  {
    place: JobPlace.Sats,
    from: new Date('2014-04-01'),
    to: new Date('2014-06-01'),
    location: 'Stockholm',
    role: 'Webbutvecklare',
    techniques: [
      Tech.ASPNETMVC,
      Tech.AngularJS,
      Tech.HTML,
      Tech.CSS,
      Tech.JavaScript,
      Tech.Photoshop,
    ],
  },
  {
    place: JobPlace.Forex,
    from: new Date('2013-02-01'),
    to: new Date('2014-03-01'),
    location: 'Stockholm',
    role: 'Webbutvecklare',
    techniques: [
      Tech.ASPNETWebforms,
      Tech.HTML,
      Tech.CSS,
      Tech.JavaScript,
      Tech.jQuery,
      Tech.Photoshop,
    ],
  },
  {
    place: JobPlace.Ineko,
    from: new Date('2012-01-07'),
    to: new Date('2013-01-01'),
    location: 'Stockholm',
    role: 'Webbutvecklare',
    techniques: [
      Tech.ASPNETWebforms,
      Tech.HTML,
      Tech.CSS,
      Tech.JavaScript,
      Tech.jQuery,
      Tech.MicrosoftSQLServer,
    ],
  },
  {
    place: JobPlace.Adlibris,
    from: new Date('2009-10-01'),
    to: new Date('2012-09-01'),
    location: 'Stockholm',
    role: 'Webbutvecklare',
    techniques: [
      Tech.ASPNETWebforms,
      Tech.HTML,
      Tech.CSS,
      Tech.JavaScript,
      Tech.jQuery,
      Tech.VBNet,
      Tech.MicrosoftSQLServer,
      Tech.Photoshop,
    ],
  },
];
